version: "2"
services:

  # ADOT Collector
  aws-ot-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    # very slow when you build it first time locally!!!
    # build:
    # context: ../
    # dockerfile: cmd/awscollector/Dockerfile
    command: ["--config=/etc/otel-agent-config.yaml"]
    #environment:
      #- AWS_REGION=us-west-2

      # Either uncomment and define these:
      #
      # - AWS_PROFILE=<profile>
      # - AWS_ACCESS_KEY_ID=<to_be_added>
      # - AWS_SECRET_ACCESS_KEY=<to_be_added>
      #
      # Or define a profile available in your shared credentials file
      #
      # - AWS_PROFILE=myprofile

    volumes:
      - /Users/vishnu/git/opentelemetry-poc/javaagent/otel-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
